name: Java CI

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
      - next
  push:
    branches:
      - master
      - next
    paths-ignore:
      - '.github/**'
      - 'docker/**'
      - 'ChangeLog.md'
      - 'README.md'

jobs:

  test:

    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/arangodb:3.8.8
          - docker.io/arangodb/arangodb:3.9.7
          - docker.io/arangodb/arangodb:3.10.2
        topology:
          - single
          - cluster
          - activefailover

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
          STARTER_MODE: ${{ matrix.topology }}
          DOCKER_IMAGE: ${{ matrix.docker-img }}
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn --no-transfer-progress test

  test-spring-boot-versions:

    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/arangodb:3.10.2
        topology:
          - single
          - cluster
        spring-boot-version:
          - 2.5.12
          - 2.6.10
          - 2.7.8

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
          cache: maven
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
          STARTER_MODE: ${{ matrix.topology }}
          DOCKER_IMAGE: ${{ matrix.docker-img }}
      - name: Info
        run: mvn -version
      - name: Install
        run: mvn --no-transfer-progress install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true
      - name: Set Spring version
        working-directory: integration-tests
        run: sed -i "0,/<version>.*<\/version>/s//<version>$SPRING_BOOT_VERSION<\/version>/" pom.xml
        env:
          SPRING_BOOT_VERSION: ${{matrix.spring-boot-version}}
      - name: Maven Deps Tree
        working-directory: integration-tests
        run: mvn dependency:tree
      - name: Test
        working-directory: integration-tests
        run: mvn --no-transfer-progress test
